version: '3.7'
services:
  php:
    image: yiisoftware/yii2-php:8.2-fpm-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - mysql
    networks:
      - yii

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - .docker/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3388:3306'
    networks:
      - yii 

volumes:
  mysql_data:

networks: 
    yii:
        driver: bridge